#!/usr/bin/env node
/**
 * T023 — ABI sync (research R4).
 * Copies forge build artifacts (contracts/out/<Contract>.sol/<Contract>.json)
 * into `frontend/src/lib/abi/` as typed TS modules with a GENERATED banner.
 * Wired to frontend `predev` / `prebuild` scripts.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'contracts', 'out');
const DEST_DIR = path.join(ROOT, 'frontend', 'src', 'lib', 'abi');

const CONTRACTS = ['EnglishAuction', 'SolimanWeb3', 'IERC721'];

const BANNER = `// GENERATED by scripts/sync-abi.mjs — DO NOT EDIT.
// Source: contracts/out/<Contract>.sol/<Contract>.json (forge build)
`;

function findArtifact(name) {
  const direct = path.join(OUT_DIR, `${name}.sol`, `${name}.json`);
  if (existsSync(direct)) return direct;
  console.error(`sync-abi: artifact not found for ${name} — run \`forge build\` first`);
  return null;
}

function main() {
  if (!existsSync(OUT_DIR)) {
    console.error('sync-abi: contracts/out missing — run `forge build` first');
    process.exit(1);
  }

  mkdirSync(DEST_DIR, { recursive: true });

  let failed = false;
  for (const name of CONTRACTS) {
    const artifactPath = findArtifact(name);
    if (!artifactPath) {
      failed = true;
      continue;
    }
    const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
    if (!Array.isArray(artifact.abi)) {
      console.error(`sync-abi: no ABI array in ${artifactPath}`);
      failed = true;
      continue;
    }
    const dest = path.join(DEST_DIR, `${name}.ts`);
    const content = `${BANNER}\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    writeFileSync(dest, content);
    console.log(`sync-abi: ${name} → frontend/src/lib/abi/${name}.ts (${artifact.abi.length} entries)`);
  }

  process.exit(failed ? 1 : 0);
}

main();
